name: Deployment to the VPS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Deploy
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          #fingerprint: ${{ secrets.FINGERPRINT }}
          port: ${{ secrets.PORT }}
          source: "target/release/otango"
          target: "."
      - name: Start Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          #fingerprint: ${{ secrets.FINGERPRINT }}
          port: ${{ secrets.PORT }}
          script: |
            mv target/release/otango otango
            sudo systemctl restart otango.service