name: Deployment to the VPS
on:
  push:
    branches: [main]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Test File
        run: echo 'Apples' > a
      - name: Test SCP
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          port: ${{ secrets.PORT }}
          source: "a"
          target: "."